# Color theme, press ":theme" to select more
theme = "Kanagawa"

# Refer https://docs.helix-editor.com/editor.html
[editor]
cursorline = true
true-color = true
mouse = false
line-number = "relative"
# Show buffer line when > 1 buffer
bufferline = "multiple"
gutters = ["diff", "line-numbers", "spacer", "diagnostics"]

# More stuff from https://github.com/maaslalani/_/blob/main/modules/helix.nix
[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true
# Show inlay hints
display-inlay-hints = true

# Cursor
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Search fully case sensitive
[editor.search]
smart-case = false

# Indent
[editor.indent-guides]
render = true

# TODO: Inline diagnostics, refer https://github.com/erasin/helix-config/blob/main/config.toml#L86

# Keymap, refer https://docs.helix-editor.com/remapping.html
# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
# q and Q for macro but doesn't use much so I map it to close buffer
q = ":buffer-close"
"S-q" = ":buffer-close"
# Save file
"C-s" = ":write"
# Save selection to jump list
"A-s" = "save_selection"
# Smart escape, credit to Luke Pighetti
esc = ["collapse_selection", "keep_primary_selection"]
# Keep the vim binding
G = "goto_last_line"
X = "extend_line_above"
# Next/prev buffer
"S-l" = ":buffer-next"
"S-h" = ":buffer-previous"
# LSP doc
"S-k" = "hover"
# Enter to next line and return to normal mode
"ret" = ["open_below", "normal_mode"]
# Expand selection
"C-space" = "expand_selection"
# File explorer, util built-in from Helix https://github.com/helix-editor/helix/pull/5768 or a plugin
# Credit to https://gist.github.com/lukepighetti/8e4a13db5bdcd68a7d83eee19051ab14
"C-e" = [
  ":new",
  ":insert-output ~/.config/helix/lf-pick.sh",
  ":theme default",
  "select_all",
  "split_selection_on_newline",
  "goto_file",
  "goto_last_modified_file",
  ":buffer-close!",
  ":theme kanagawa",
  ":redraw",
]

[keys.normal."space"]
h = ":open ~/.config/helix/config.toml"
q = { q = ":quit-all" }
l = { f = ":format" }
w = { r = ":reload", c = ":config-reload" }
"." = "file_picker_in_current_buffer_directory"
"," = "buffer_picker"
"space" = "file_picker"

# Toggle
t = { h = ":toggle file-picker.hidden", f = ":toggle auto-format", i = ":toggle lsp.display-inlay-hints" }
